name: "Build and Publish"

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/workflows/ci.yaml"
  schedule:
    # Always run at least once a month to regularly rebuild the image .
    - cron: "0 0 1 * *"
  workflow_dispatch:

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "djmattyg007/jsonnet"

jobs:
  main:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      packages: "write"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3" # v6.0.0

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130" # v3.7.0

      - name: "Set up Docker Buildkit"
        uses: "docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435" # v3.11.1

      - name: "Log in to the container registry"
        uses: "docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef" # v3.6.0
        with:
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Get version for image tag"
        id: "get-version"
        run: |
          echo "version=$(grep -m1 'JSONNET_VERSION' < Dockerfile | awk -F "\"" '{print $2}')" >> "${GITHUB_OUTPUT}"
        shell: "bash"

      - name: "Extract metadata (tags, labels) for Docker"
        id: "meta"
        uses: "docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051" # v5.10.0
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          tags: |
            type=semver,pattern={{version}},value=${{ steps.get-version.outputs.version }}

      - name: "Build and push image"
        uses: "docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83" # v6.18.0
        with:
          context: "."
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
          platforms: "linux/amd64,linux/arm64,linux/arm/v7"
