name: "CI"

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  schedule:
    # Always run at least once a month to regularly run the tests with
    # recent software versions.
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2

      - name: "Run Hadolint"
        uses: "hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5" # v3.3.0

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130" # v3.7.0

      - name: "Set up Docker Buildkit"
        uses: "docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f" # v3.12.0

      - name: "Build container image"
        uses: "docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8" # v6.19.2
        with:
          context: "."
          push: false
          platforms: "linux/amd64,linux/arm64,linux/arm/v7"
