name: "CI"

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  schedule:
    # Always run at least once a month to regularly run the tests with
    # recent software versions.
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8" # v6.0.1

      - name: "Run Hadolint"
        uses: "hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5" # v3.3.0

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130" # v3.7.0

      - name: "Set up Docker Buildkit"
        uses: "docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435" # v3.11.1

      - name: "Build container image"
        uses: "docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83" # v6.18.0
        with:
          context: "."
          push: false
          platforms: "linux/amd64,linux/arm64,linux/arm/v7"
